// PIS
// RECIVER
export const TOPIC_MODAL_REMOVE_PRODUCT = import.meta.env
  .VITE_TOPIC_MODAL_REMOVE_PRODUCT;
export const TOPIC_MODAL_REMOVE_VARIANT = import.meta.env
  .VITE_TOPIC_MODAL_REMOVE_VARIANT;
export const TOPIC_MODAL_REMOVE_SETTING = import.meta.env
  .VITE_TOPIC_MODAL_REMOVE_SETTING;
export const TOPIC_MODAL_CANCEL_ADD = import.meta.env
  .VITE_TOPIC_MODAL_CANCEL_ADD;
export const TOPIC_TOAST_CREATE_UPDATE_PRODUCT = import.meta.env
  .VITE_TOPIC_TOAST_CREATE_UPDATE_PRODUCT;
export const TOPIC_TOAST_REMOVE_PRODUCT = import.meta.env
  .VITE_TOPIC_TOAST_REMOVE_PRODUCT;
export const TOPIC_REDIRECT = import.meta.env.VITE_TOPIC_REDIRECT;

// SENDER
export const TOPIC_RESP_REMOVE_PRODUCT = import.meta.env
  .VITE_TOPIC_RESP_REMOVE_PRODUCT;
export const TOPIC_RESP_REMOVE_VARIANT = import.meta.env
  .VITE_TOPIC_RESP_REMOVE_VARIANT;
export const TOPIC_RESP_REMOVE_SETTING = import.meta.env
  .VITE_TOPIC_RESP_REMOVE_SETTING;
